# Generated by Django 4.1.5 on 2023-07-23 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('que', models.CharField(max_length=255)),
                ('ans', models.TextField(max_length=555)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('app_email', models.EmailField(max_length=100)),
                ('app_mobile', models.CharField(max_length=20)),
                ('app_address', models.TextField(max_length=150)),
                ('app_version', models.CharField(max_length=20)),
                ('app_logo', models.FileField(upload_to='upload/')),
                ('app_fevicon', models.FileField(upload_to='upload/')),
                ('app_stamp', models.FileField(upload_to='upload/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sites',
            },
        ),
    ]
