# Generated by Django 4.2.14 on 2024-08-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinerequest',
            old_name='packages',
            new_name='services',
        ),
        migrations.RemoveField(
            model_name='onlinerequest',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='onlinerequest',
            name='webtype',
        ),
    ]
