from django.urls import path, include

from .views import (
    WebDev,
    ServicesListViews,
    ServicesDetailViews,
    PersonalSites,
    Ecommerce,
    Corporate,
    Cms,
    Hrm,
    Portfollio,
    StaticSites,
    Blogs,
    DynamicWeb,
    BasicPack,
    StaticPackPrice,
    StaticPackPriceDetail,
    DynamicPackPriceDetail,
    CorporatePackPriceDetail,
    EcommercePackPriceDetail,
    LogoDesignView,
    CustomLogoDesignView,
    LogoReDesignView,
    BrandLogoDesignView,
    QuickCommerceView,
    CustomQuickCommerceView,
    QuickCommercePayementView,
    PerformanceAnalysisView,
    SoftDevView,
    GraphicsView,
    GraphicsSmView,
    GraphicsPackView,
    MarketingGraphicsView,
    DomainBookingView,
    DigitalMarketingView,
    SeoView,
)

app_name = "services"
urlpatterns = [
    path("seo/", SeoView.as_view(), name="seo"),
    path("digital-marketing/", DigitalMarketingView.as_view(), name="digital_marketing"),
    path("domain-booking/", DomainBookingView.as_view(), name="domain_booking"),
    path("marketing-graphics-designing/", MarketingGraphicsView.as_view(), name="marketing"),
    path("packing-graphics-designing/", GraphicsPackView.as_view(), name="graphics_pack"),
    path("social-media-graphics-designing/", GraphicsSmView.as_view(), name="graphics_sm"),
    path("graphics-designing/", GraphicsView.as_view(), name="graphics"),
    path("software-development/", SoftDevView.as_view(), name="soft_dev"),
    path("qucik-commerce-performance-analysis/", PerformanceAnalysisView.as_view(), name="quick_commerce_performance_analysis"),
    path("QucikCommercePaymentGetway/", QuickCommercePayementView.as_view(), name="quick_commerce_payment"),
    path("custom-qucik-commerce/", CustomQuickCommerceView.as_view(), name="custom_quick_commerce"),
    path("cucik-commerce/", QuickCommerceView.as_view(), name="quick_commerce"),
    path("custome-logo-design/", CustomLogoDesignView.as_view(), name="custom_logo_design"),
    path("brand-logo-design/", BrandLogoDesignView.as_view(), name="brand_logo_design"),
    path("logo-redesign/", LogoReDesignView.as_view(), name="logo_redesign"),
    path(
        "services/ecommerce-pack-detail",
        EcommercePackPriceDetail.as_view(),
        name="ecommerce_pack_detail",
    ),
    path("logo-design/", LogoDesignView.as_view(), name="logo_design"),
    path(
        "services/ecommerce-pack-detail",
        EcommercePackPriceDetail.as_view(),
        name="ecommerce_pack_detail",
    ),
    path(
        "services/corporate-pack-detail",
        CorporatePackPriceDetail.as_view(),
        name="corporate_pack_detail",
    ),
    path(
        "services/dynamic-pack-detail",
        DynamicPackPriceDetail.as_view(),
        name="dynamic_pack_detail",
    ),
    path(
        "services/static-pack-detail",
        StaticPackPriceDetail.as_view(),
        name="static_pack_price_detail",
    ),
    path(
        "services/static-pack-prices",
        StaticPackPrice.as_view(),
        name="static_pack_price",
    ),
    path(
        "services/basic-pack",
        BasicPack.as_view(),
        name="basic_pack",
    ),
    path(
        "services/web-services",
        WebDev.as_view(),
        name="web_dev",
    ),
    path(
        "services/dynamic-web",
        DynamicWeb.as_view(),
        name="dynamic_web",
    ),
    path(
        "services/personal-sites",
        PersonalSites.as_view(),
        name="personal_sites",
    ),
    path(
        "services/ecommerce",
        Ecommerce.as_view(),
        name="online_stores",
    ),
    path("services/corporate-web", Corporate.as_view(), name="corporate"),
    path("services/cms", Cms.as_view(), name="cms"),
    path("services/hrm", Hrm.as_view(), name="hrm"),
    path("services/portfolio", Portfollio.as_view(), name="portfollio"),
    path("services/blogs", Blogs.as_view(), name="blogs"),
    path("services/static-sites", StaticSites.as_view(), name="static_sites"),
    path("services/", ServicesListViews.as_view(), name="services"),
    path("services/<uuid:pk>", ServicesDetailViews.as_view(), name="service_detail"),
]
